apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-novel-cockatoo
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "722293036635"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: playground-s-11-098c0d34
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: Git-Organisation
    repository: jenkinsxcluster
  - key: staging
  - key: production
  ingress:
    domain: 35.226.111.205.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: kushwap1
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-novel-cockatoo-17b812f16748
  - name: reports
    url: gs://reports-tf-jx-novel-cockatoo-17b812f16748
  - name: repository
    url: gs://repository-tf-jx-novel-cockatoo-17b812f16748
  vault: {}
  webhook: lighthouse
